In [3]:
from pathlib import Path
import cv2
import numpy as np

In [4]:
calibration_images_path = Path.cwd() / Path('tests') / Path('images')
calibration_images = tuple(calibration_images_path.glob('left*'))
calibration_images[5]

PosixPath('/home/jsk/GitHub/cv2stuff/cv2stuff/tests/images/left12.jpg')

In [5]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
criteria

(3, 30, 0.001)

In [6]:
pattern_dimensions = (9, 6) # The inner corners of the sample chessboard image.
dimensions_product = pattern_dimensions[0] * pattern_dimensions[1]

In [7]:
objp = np.zeros((dimensions_product,3), np.float32) # empty array
objp[:,:2] = np.mgrid[0:pattern_dimensions[0],0:pattern_dimensions[1]].T.reshape(-1,2) # index the array

In [8]:
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

In [9]:
fname = str(calibration_images[0])

In [10]:
img = cv2.imread(fname)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [11]:
ret, corners = cv2.findChessboardCorners(gray, pattern_dimensions, None)
ret

True

In [12]:
objpoints.append(objp)
objpoints

[array([[ 0.,  0.,  0.],
        [ 1.,  0.,  0.],
        [ 2.,  0.,  0.],
        [ 3.,  0.,  0.],
        [ 4.,  0.,  0.],
        [ 5.,  0.,  0.],
        [ 6.,  0.,  0.],
        [ 7.,  0.,  0.],
        [ 8.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 1.,  1.,  0.],
        [ 2.,  1.,  0.],
        [ 3.,  1.,  0.],
        [ 4.,  1.,  0.],
        [ 5.,  1.,  0.],
        [ 6.,  1.,  0.],
        [ 7.,  1.,  0.],
        [ 8.,  1.,  0.],
        [ 0.,  2.,  0.],
        [ 1.,  2.,  0.],
        [ 2.,  2.,  0.],
        [ 3.,  2.,  0.],
        [ 4.,  2.,  0.],
        [ 5.,  2.,  0.],
        [ 6.,  2.,  0.],
        [ 7.,  2.,  0.],
        [ 8.,  2.,  0.],
        [ 0.,  3.,  0.],
        [ 1.,  3.,  0.],
        [ 2.,  3.,  0.],
        [ 3.,  3.,  0.],
        [ 4.,  3.,  0.],
        [ 5.,  3.,  0.],
        [ 6.,  3.,  0.],
        [ 7.,  3.,  0.],
        [ 8.,  3.,  0.],
        [ 0.,  4.,  0.],
        [ 1.,  4.,  0.],
        [ 2.,  4.,  0.],
        [ 3.,  4.,  0.],


In [13]:
cv2.cornerSubPix(gray, corners,(11,11), (-1,-1), criteria)

array([[[ 188.52177429,  130.59634399]],

       [[ 223.25431824,  127.10599518]],

       [[ 260.33712769,  123.72382355]],

       [[ 299.31347656,  120.21031189]],

       [[ 340.14273071,  117.28233337]],

       [[ 382.4118042 ,  114.39073181]],

       [[ 425.84460449,  112.19089508]],

       [[ 470.29394531,  110.21006012]],

       [[ 514.56268311,  109.15750885]],

       [[ 185.58255005,  168.31446838]],

       [[ 220.92555237,  165.8598175 ]],

       [[ 258.52218628,  163.19372559]],

       [[ 298.12036133,  160.62052917]],

       [[ 339.50344849,  158.407547  ]],

       [[ 382.67443848,  156.35827637]],

       [[ 427.01651001,  154.53375244]],

       [[ 472.39154053,  153.32444763]],

       [[ 517.5065918 ,  152.16775513]],

       [[ 183.30487061,  207.50357056]],

       [[ 218.83789062,  205.89527893]],

       [[ 256.93572998,  204.27267456]],

       [[ 297.06646729,  202.78793335]],

       [[ 338.93032837,  201.50622559]],

       [[ 382.76010132,  200.21937

In [14]:
imgpoints.append(corners)

In [15]:
cv2.drawChessboardCorners(img, pattern_dimensions, corners, ret)

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  1,  1],
        ..., 
        [ 0,  0,  0],
        [ 5,  5,  5],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 1,  1,  1],
        [ 3,  3,  3],
        ..., 
        [ 6,  6,  6],
        [12, 12, 12],
        [ 1,  1,  1]],

       [[ 2,  2,  2],
        [ 3,  3,  3],
        [ 5,  5,  5],
        ..., 
        [10, 10, 10],
        [14, 14, 14],
        [ 0,  0,  0]],

       ..., 
       [[10, 10, 10],
        [37, 37, 37],
        [41, 41, 41],
        ..., 
        [61, 61, 61],
        [48, 48, 48],
        [ 6,  6,  6]],

       [[ 8,  8,  8],
        [34, 34, 34],
        [35, 35, 35],
        ..., 
        [43, 43, 43],
        [41, 41, 41],
        [ 8,  8,  8]],

       [[ 0,  0,  0],
        [11, 11, 11],
        [10, 10, 10],
        ..., 
        [ 9,  9,  9],
        [13, 13, 13],
        [ 0,  0,  0]]], dtype=uint8)

In [16]:
cv2.imshow('img', img)
cv2.waitKey(500)
cv2.destroyAllWindows()

In [17]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [18]:
fname = str(calibration_images[5])

In [19]:
img = cv2.imread(fname)

In [20]:
h, w = img.shape[:2]
h, w

(480, 640)

In [21]:
newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (w, h), 1, (w, h))
#newcameramtx, roi
roi

(0, 0, 0, 0)

In [22]:
# undistort
dst = cv2.undistort(img, mtx, dist, None, newcameramtx)
dst

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ..., 
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ..., 
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ..., 
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       ..., 
       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ..., 
        [91, 91, 91],
        [91, 91, 91],
        [91, 91, 91]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ..., 
        [94, 94, 94],
        [93, 93, 93],
        [87, 87, 87]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ..., 
        [93, 93, 93],
        [88, 88, 88],
        [79, 79, 79]]], dtype=uint8)

In [23]:
# crop the image
#x,y,w,h = roi
#dst = dst[y:y+h, x:x+w]

cal_image = str(calibration_images_path) + '/' + 'calibresult.jpg'

written = cv2.imwrite(cal_image, dst)
roi, dst, cal_image

((0, 0, 0, 0), array([[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ..., 
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ..., 
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ..., 
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        ..., 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ..., 
         [91, 91, 91],
         [91, 91, 91],
         [91, 91, 91]],
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ..., 
         [94, 94, 94],
         [93, 93, 93],
         [87, 87, 87]],
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ..., 
         [93, 93, 93],
         [88, 88, 88],
         [79, 79, 79]]], dtype=uint8), '/home/jsk/GitHub/cv2st

In [24]:
# undistort
mapx, mapy = cv2.initUndistortRectifyMap(mtx, dist, None, newcameramtx, (w,h), 5)
mapx, mapy

(array([[  8.62281200e+06,   8.54637200e+06,   8.47056100e+06, ...,
          -2.88052656e+05,  -2.91261188e+05,  -2.94498312e+05],
        [  8.56564100e+06,   8.48957800e+06,   8.41414200e+06, ...,
          -2.84118625e+05,  -2.87288906e+05,  -2.90487500e+05],
        [  8.50886600e+06,   8.43317900e+06,   8.35811500e+06, ...,
          -2.80230312e+05,  -2.83362719e+05,  -2.86523188e+05],
        ..., 
        [  1.65388300e+06,   1.63096462e+06,   1.60831988e+06, ...,
           1.12884987e+02,   8.99150772e+01,   6.60684128e+01],
        [  1.65771762e+06,   1.63476125e+06,   1.61207875e+06, ...,
           9.89884262e+01,   7.56405411e+01,   5.14069099e+01],
        [  1.66160638e+06,   1.63861125e+06,   1.61589050e+06, ...,
           8.47291107e+01,   6.09951248e+01,   3.63662453e+01]], dtype=float32),
 array([[  7.57184200e+06,   7.51999000e+06,   7.46847950e+06, ...,
           8.62801312e+05,   8.66407000e+05,   8.70047688e+05],
        [  7.50272350e+06,   7.45123100e+06, 

In [26]:
dst = cv2.remap(img, mapx, mapy, cv2.INTER_LINEAR)
dst

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ..., 
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ..., 
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ..., 
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       ..., 
       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ..., 
        [91, 91, 91],
        [91, 91, 91],
        [91, 91, 91]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ..., 
        [94, 94, 94],
        [93, 93, 93],
        [87, 87, 87]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ..., 
        [93, 93, 93],
        [88, 88, 88],
        [79, 79, 79]]], dtype=uint8)